#!/bin/bash
# start-mc.sh — start Mission Control with auth enabled
# Generated by NofiTech-Ind on 2026-06-17

export MC_ADMIN_TOKEN="dev-secret-nofitech-2026-bf-90-aa-7e-3c-12"
cd /home/nofidofi/NofiTech-Ind/01_projects/mission-control/code
exec python3 serve.py
